const asyncHandler = require('../utils/asyncHandler');
const { ApiResponse, ApiError } = require('../utils/apiResponse');
const paymentService = require('../services/paymentService');

const createPayment = asyncHandler(async (req, res) => {
  const { orderId } = req.body;
  if (!orderId) {
    throw new ApiError(400, 'Order ID is required');
  }

  const paymentData = await paymentService.createPayment(orderId, req.user._id);
  res.status(200).json(new ApiResponse(200, paymentData, 'Payment initialized'));
});

const verifyPayment = asyncHandler(async (req, res) => {
  const { razorpay_order_id, razorpay_payment_id, razorpay_signature } = req.body;
  
  if (!razorpay_order_id || !razorpay_payment_id || !razorpay_signature) {
    throw new ApiError(400, 'Missing payment verification payloads');
  }

  const payment = await paymentService.verifyPaymentSignature(req.user._id, {
    razorpay_order_id,
    razorpay_payment_id,
    razorpay_signature,
  });

  res.status(200).json(new ApiResponse(200, { payment }, 'Payment verified successfully'));
});

const handleWebhook = asyncHandler(async (req, res) => {
  const signature = req.headers['x-razorpay-signature'];
  if (!signature) {
    throw new ApiError(400, 'Missing webhook signature');
  }
  
  if (!req.rawBody) {
    throw new ApiError(400, 'Raw body missing');
  }

  // req.rawBody is generated by express.json() verify function
  await paymentService.handleWebhook(req.rawBody, signature);
  
  res.status(200).json({ status: 'ok' });
});

module.exports = {
  createPayment,
  verifyPayment,
  handleWebhook,
};
